import Head from 'next/head'
import { supabase } from 'components/utils/supabase/client'
import { useRouter } from 'next/router'
export default function Login() {
    const router = useRouter();
  const logout = async () => {
    const { error } = await supabase.auth.signOut()
    
    console.log(error)
  }
  
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button className="button button-primary" onClick={logout}>Logout</button>
        
      </main>
    </>
  )
}
