import Navigation from 'components/elements/website/Navigation'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs tailwind starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>
      <main>
        <div>
          <p>
            Tailwind nextjs starter
          </p>
        </div>
      </main>
    </>
  )
}
