import Head from 'next/head'
import { supabase } from 'components/utils/supabase/client'
import Navigation from 'components/elements/app/Navigation'
export default function Profile() {
  const logout = async () => {
    const { error } = await supabase.auth.signOut()
    console.log(error)
  }
  
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>
      <main className="">
        <button className="button button-danger" onClick={logout}>Logout</button>
      </main>
    </>
  )
}
